name: Deploy ðŸ§ðŸ©

on:
  push:
    branches: [ "master", "develop", "feature/**" ]
  pull_request:
    branches: [ "master", "develop", "feature/**" ]

env:
  PROJECT_NAME: samokatim-client-ui
  NAMESPACE_NAME: samokatim-frontend
  EXTERNAL_PORT: 80
  APP_PORT: 80
  NODE_NO_WARNINGS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: CI=false npm run build --if-present
      - name: Docker Hub login
        run: docker login --username ${{ secrets.USERNAME_HUB }} --password ${{ secrets.PASSWORD_HUB }}
      - name: Docker build
        run: docker build --tag ${{ secrets.USERNAME_HUB }}/$PROJECT_NAME:$GITHUB_RUN_NUMBER .
      - name: Docker push
        run: docker push ${{ secrets.USERNAME_HUB }}/$PROJECT_NAME:$GITHUB_RUN_NUMBER
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        run: sudo snap install helm --classic
      - name: Deploy to server
        run: |
          echo "${{secrets.KUBECONFIG}}" > ~/kubeconfig
          helm upgrade --kubeconfig ~/kubeconfig --set image.tag=$GITHUB_RUN_NUMBER -n $NAMESPACE_NAME $PROJECT_NAME helm/
